from .base import BaseParadigmWidget
from .rest import RestParadigm
from .rest_break import RestBreakParadigm
from .dotprobe import DotProbeTask
from .painting import PaintingTask
from .music import MusicTask
from .vr import VRTask
from .voice_reading import VoiceReadingTask
from .voice_interview import VoiceInterviewTask
from .image_describe import ImageDescribeTask
